apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redisinsight.fullname" . }}-data
  labels:
    {{- include "redisinsight.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- with .Values.persistence.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
